name: flutter_memory_client
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  web_socket_channel: ^2.4.0
  provider: ^6.0.5
  window_manager: ^0.3.7
  path_provider: ^2.1.1
  file_selector: ^0.9.0
  toastification: ^1.1.0
  stroke_text: any
  loading_animation_widget: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - ./assets/header!.png
